name: koi_one_line
description: "Library that can do a lot of things. Only takes 1 line of code :)"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - packages/koi_one_line/assets/undraw_access_denied_re_awnf.svg
    - packages/koi_one_line/assets/undraw_back_home_nl-5-c.svg
    - packages/koi_one_line/assets/undraw_counting_stars_re_smvv.svg
    - packages/koi_one_line/assets/undraw_donut_love_kau1.svg
    - packages/koi_one_line/assets/undraw_dream_world_re_x2yl.svg
    - packages/koi_one_line/assets/undraw_dreamer_re_9tua.svg
    - packages/koi_one_line/assets/undraw_fixing_bugs_w7gi.svg
    - packages/koi_one_line/assets/undraw_loading_re_5axr.svg
    - packages/koi_one_line/assets/undraw_logic_re_nyb4.svg
    - packages/koi_one_line/assets/undraw_page_not_found_re_e9o6.svg
    - packages/koi_one_line/assets/undraw_problem_solving_re_4gq3.svg
    - packages/koi_one_line/assets/undraw_step_to_the_sun_nxqq.svg
    - packages/koi_one_line/assets/undraw_synchronize_re_4irq.svg
    - packages/koi_one_line/assets/undraw_under_construction_-46-pa.svg
    - packages/koi_one_line/assets/undraw_winter_road_mcqj.svg
    - packages/koi_one_line/assets/undraw_refreshing_beverage_td3r.svg
    - packages/koi_one_line/assets/undraw_monster_artist_2crm.svg
    - packages/koi_one_line/assets/undraw_joyride_re_968t.svg
    - packages/koi_one_line/assets/undraw_mint_tea_-7-su0.svg
    - packages/koi_one_line/assets/undraw_decide_re_ixfw.svg
    - packages/koi_one_line/assets/undraw_quick_chat_re_bit5.svg
    - packages/koi_one_line/assets/undraw_taken_re_yn20.svg
    - packages/koi_one_line/assets/undraw_happy_music_g6wc.svg
    - packages/koi_one_line/assets/undraw_walk_dreaming_u-58-a.svg

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
